Web/siteWebProjetIOT/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#logout'
  post 'login', to: 'sessions#create'

  resources :users, only: [:index, :new, :edit, :create, :update, :destroy]

  resources :trucks do #index, show, new, edit, create, update, destroy
    get "truckInfoImages/:id", action: :truckInfoImages, as: 'images'
  end

  get 'api/addTruckInfo', to: 'trucks#addTruckInfo'
  post 'api/addTruckInfo', to: 'trucks#addTruckInfo'

  get 'testApi', to: 'sessions#testApi'

  mount ActionCable.server => '/cable'
end

Web/siteWebProjetIOT/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

Web/siteWebProjetIOT/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :admin_authorized, except: [:edit, :update]
  skip_before_action :change_password, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    #set_user
    redirect_to root_path, notice: "Not Authorized" unless logged_in? and (is_admin? or @user.id == current_user.id)
    if current_user == @user and !@user.initialized
      @otp_secret = ROTP::Base32.random
      @user.otp_secret = @otp_secret
      totp = ROTP::TOTP.new( @otp_secret, issuer: 'Safe-Truck' )
      @qr = RQRCode::QRCode.new(totp.provisioning_uri(@user.username)).as_svg(
        offset: 0,
        color: '000',
        shape_rendering: 'crispEdges',
        module_size: 6,
        standalone: true,
        viewbox: true
      )
    end
  end

  def create
    @user = User.new(user_admin_params)
    @user.password_digest = BCrypt::Password.create("TemporaryPassword")
    if !User.find_by_username(@user.username) 
      if @user.save
        redirect_to users_path, notice: "User created"
      else
        render :new, status: :unprocessable_entity
      end
    else
      flash.now[:notice] = "User already exists"
      render :new
    end
  end

  def update
    otpEnabled = false;
    #set_user
    redirect_to root_path, notice: "Not Authorized" unless logged_in? and (is_admin? or @user.id == current_user.id)
    #to prevent disabling admin permissions of last admin
    admins = User.where(:admin_permissions => true)
    if (admins.length == 1 and @user == admins.last and user_admin_params[:admin_permissions] == "0") 
      redirect_to users_path, notice: "Can't change this permission because he is the last admin"
      return
    end
    if @user == current_user and !@user.initialized
      @otp_secret = user_params[:otp_secret]
      totp = ROTP::TOTP.new(@otp_secret, issuer: 'Safe-Truck')
      last_otp_at = totp.verify(params[:otp_attempt], drift_behind: 15)

      if last_otp_at
        otpEnabled = true
      else
        flash.now[:notice] = 'The code you provided was invalid!'
        redirect_to edit_user_path(@user)
        return
      end
    end

    if (!is_admin? and @user.update(user_params)) or (is_admin? and @user.update(user_admin_params))
      if !@user.initialized and !params[:user][:password].blank? and otpEnabled
        @user.initialized = true
        @user.last_otp_at = last_otp_at
        @user.otp_secret = @otp_secret
        @user.save
      end
      redirect_to users_path, notice: "User updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    #set_user
    admins = User.where(:admin_permissions => true)
    if !(admins.length == 1 and @user == admins.last)
      @user.destroy
      redirect_to users_path, notice: "User was successfully destroyed."
    else
      redirect_to users_path, notice: "Can't remove this user because he is the last admin"
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :otp_secret, :otp_attempt)
  end

  def user_admin_params
    params.require(:user).permit(:username, :password, :password_confirmation, :admin_permissions)
  end
end

Web/siteWebProjetIOT/app/helpers/users_helper.rb
module UsersHelper
end

Web/siteWebProjetIOT/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for( @user , url: user_path ) do |f| %>
    <div class="Userflex">
        <div class="Userleft">
            <%= f.hidden_field :otp_secret %>
            <p><%= @user.username %></p>
            <% if current_user.id == @user.id %>
                <%= f.label :password, "New password" %>
                <%= f.password_field :password %>
                <%= f.label :password_confirmation, "New password confirmation" %>
                <%= f.password_field :password_confirmation %>
            <% end %>
            <% if is_admin? %>
                <%= f.label :admin_permissions, "admin permissions" %>
                <%= f.check_box :admin_permissions %>
            <% end %>
        </div>
        <% if logged_in? and current_user == @user and !@user.initialized %>
            <div class="Userright">
                <h3>2 Factor Authentication (Google Authenticator ou Authy):</h3>
                <%= @qr.html_safe %>
                <%= label_tag  :otp_attempt, "Verify (enter a one-time password)" %>
                <%= text_field_tag :otp_attempt %>
            </div>
        <% end %>
    </div>
    <%= f.submit "Save" %>
<% end %>

Web/siteWebProjetIOT/app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to "New User", new_user_path, class: "addButton" %>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Initialized?</th>
      <th>Admin?</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.initialized %></td>
        <td><%= user.admin_permissions %></td>
 <%
=begin%>
 <td><%= link_to 'Show', user %></td> 
<%
=end%>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Web/siteWebProjetIOT/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%
=begin%>
 <%= f.label :password%>
  <%= f.password_field :password%>
  <%= f.label :password_confirmation%>
  <%= f.password_field :password_confirmation%> 
<%
=end%>
  <%= f.label :admin_permissions, "admin permissions" %>
  <%= f.check_box :admin_permissions %>
  <%= f.submit %>
<%end%>