Web/siteWebProjetIOT/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#logout'
  post 'login', to: 'sessions#create'

  resources :users, only: [:index, :new, :edit, :create, :update, :destroy]

  resources :trucks do #index, show, new, edit, create, update, destroy
    get "truckInfoImages/:id", action: :truckInfoImages, as: 'images'
  end

  get 'api/addTruckInfo', to: 'trucks#addTruckInfo'
  post 'api/addTruckInfo', to: 'trucks#addTruckInfo'

  get 'testApi', to: 'sessions#testApi'

  mount ActionCable.server => '/cable'
end

Web/siteWebProjetIOT/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteWebProjetIOT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Pour la carte -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin=""></script>
    
    <%= yield :head %>
    
  </head>

  <body>
    <nav>
      <%= link_to "Home", root_path %>
      <div class="spacer"></div>
      <% if not logged_in? %>
        <%= link_to "Login", login_path %>
      <% else %>
        <% if is_admin? %>
          <%= link_to "Users", users_path %>
        <% end %>
        <%= link_to "Trucks", trucks_path %>
        <%= link_to "Logout", logout_path %>
        <%= link_to current_user.username, edit_user_path(current_user) %>
      <% end %>
    </nav>
    <p id="notice"><%= flash[:notice] %></p>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>