Web/siteWebProjetIOT/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#logout'
  post 'login', to: 'sessions#create'

  resources :users, only: [:index, :new, :edit, :create, :update, :destroy]

  resources :trucks do #index, show, new, edit, create, update, destroy
    get "truckInfoImages/:id", action: :truckInfoImages, as: 'images'
  end

  get 'api/addTruckInfo', to: 'trucks#addTruckInfo'
  post 'api/addTruckInfo', to: 'trucks#addTruckInfo'

  get 'testApi', to: 'sessions#testApi'

  mount ActionCable.server => '/cable'
end

Web/siteWebProjetIOT/app/models/truck.rb
class Truck < ApplicationRecord
    has_many :truck_infos, dependent: :destroy

    def lastTruckMapInfo
        truck_infos.select(:lat, :lon, :fuel_level, :is_stolen, :created_at).last
    end
end

Web/siteWebProjetIOT/app/controllers/trucks_controller.rb
require 'rqrcode'

class TrucksController < ApplicationController
    skip_before_action :authorized, only: [:addTruckInfo]
    skip_before_action :verify_authenticity_token, only: [:addTruckInfo]
    before_action :set_truck, only: [:show, :edit, :update, :destroy]
    before_action :admin_authorized, only: [:edit, :update, :destory]

    def index
        @trucks = Truck.all
    end

    def show
        #set_truck
        @truckInfos = @truck.truck_infos.order(created_at: :desc)
        @qr = RQRCode::QRCode.new(@truck.hex_identifier).as_svg(
            offset: 0,
            color: '000',
            shape_rendering: 'crispEdges',
            module_size: 6,
            standalone: true,
            viewbox: true
        )
    end

    def new
        @truck = Truck.new
    end
    
    def create
        @truck = Truck.new(truck_params)
        randomhex = SecureRandom.hex(16) #Generate a 32 char long Hex number
        
        while Truck.exists?(hex_identifier: randomhex)
            randomhex = SecureRandom.hex(16) #Generate a 32 char long Hex number
            puts("whileloop")
        end

        @truck.hex_identifier = randomhex
        
        if @truck.save
            redirect_to @truck, notice: "Truck created"
        else
            render :new, status: :unprocessable_entity
        end
    end
    

    def edit
        #set_truck
    end

    def update
        #set_truck
        if @truck.update(truck_params)
            redirect_to trucks_path, notice: "Truck updated"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        #set_truck
        json = @truck.as_json(only: [:hex_identifier]);
        json["delete"] = true
        @truck.destroy
        ActionCable.server.broadcast('messages_channel', message: json.to_json())
        redirect_to trucks_path, notice: "Truck was succesfully destroyed"
    end

    def addTruckInfo
        if request.get?
            render :json => {:description => "API endpoint to add data from trucks"}
        else 
            if truck_infos_params[:hex_identifier]
                if truck = Truck.find_by(hex_identifier: truck_infos_params[:hex_identifier])
                    if truck.truck_infos.create(truck_infos_params.permit(:is_stolen, :fuel_level, :lat, :lon, images: []))
                        json = truck.to_json(only: [:id, :hex_identifier, :name], methods: :lastTruckMapInfo)
                        ActionCable.server.broadcast('messages_channel', message: json)
                        render :json => {:status => "Created"}
                    else
                        render :json => {:status => "Internal server Error"}, status: :internal_server_error
                    end
                else
                    render :json => {:status => "Identifier not recognized"}, status: :bad_request
                end
            else
                render :json => {:status => "Not authorized"}, status: :unauthorized
            end
        end
    end

    def truckInfoImages
        @truck = Truck.find(params[:truck_id])
        @truckinfoimages = @truck.truck_infos.find(params[:id]).images
    end

    private
    def set_truck
        @truck = Truck.find(params[:id])
    end

    def truck_params
        params.require(:truck).permit(:name, :description)
    end

    def truck_infos_params
        params.permit(:hex_identifier, :is_stolen, :fuel_level, :lat, :lon, images: [])
    end
end

Web/siteWebProjetIOT/app/helpers/trucks_helper.rb
module TrucksHelper
end

Web/siteWebProjetIOT/app/views/trucks/edit.html.erb
<h1>Edit Truck</h1>

<%= form_for( @truck, url: truck_path) do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
    <%= f.submit "Save" %>
<% end %>

Web/siteWebProjetIOT/app/views/trucks/index.html.erb
<h1>Liste des camions</h1>

<%= link_to "Add Truck", new_truck_path, class: "addButton" %> 

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.hex_identifier %></td>
        <td><%= truck.name %></td>
        <td><%= truck.description %></td>
        <td><%= link_to 'Show', truck %></td> 
        <% if is_admin? %>
          <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
          <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

Web/siteWebProjetIOT/app/views/trucks/new.html.erb
<h1>Add Truck</h1>
<%= form_for @truck do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>
  <%= f.submit %>
<%end%>

Web/siteWebProjetIOT/app/views/trucks/show.html.erb
<h1><%= @truck.name %></h1>

<div class="flex">
  <div class="left">
    <p>Identifiant : <%= @truck.hex_identifier %></p>
    <p>Description : <br><%= @truck.description %></p>
  </div>
  <div class="right">
    <p>QR code à scanner par l'application du camion :</p>
    <%= @qr.html_safe %>
  </div>
</div>

<h2>Listes des évenements :</h2>

<table>
  <thead>
    <tr>
      <th>Is_stolen</th>
      <th>Fuel level</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Created at</th>
      <th>Images</th>
    </tr>
  </thead>

  <tbody>
    <% @truckInfos.each do |truckInfo| %>
      <tr <%= truckInfo.is_stolen ? "class=stolen" : "" %>>
        <td><%= truckInfo.is_stolen %></td>
        <td><%= truckInfo.fuel_level %>%</td>
        <td><%= truckInfo.lat %></td>
        <td><%= truckInfo.lon %></td>
        <td><%= truckInfo.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td>
          <% if truckInfo.images.attached? %>
            <%= link_to "Voir images", truck_images_path(truckInfo.truck_id, truckInfo) %>
          <% else %>
            Pas d'images
          <% end %>
        </td>
    <% end %>
  </tbody>
</table>

Web/siteWebProjetIOT/app/views/trucks/truckInfoImages.html.erb
<h1>Images de <%= @truck.name %></h1>

<%= link_to "Liste des infos", truck_path(@truck) %>

<div class="images">
    <% if @truckinfoimages.attached? %> 
        <% @truckinfoimages.each do |image| %>
            <%= image_tag image, height: "300px" %>
        <% end %>
    <% else %>
        <p>Pas d'images</p>
    <% end %>
</div>